apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: app-back
spec:
  selector:
    matchLabels:
      app: app-back
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: app-back
    spec:
      containers:
        - name: app-back
          image: hajarnaityahia973/app-back:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8066 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: app-back-service
spec:
  selector:
    app: app-back
  ports:
    - protocol: "TCP"
      port: 8066 # The port that the service is running on in the cluster
      targetPort: 8066 # The port exposed by the service
  type: LoadBalancer # type of the service.