apiVersion: v1
kind: Service
metadata:
  name: app-back-service
spec:
  selector:
    app: app-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8066
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
